### ISSUE TITLE
Feature:  ReadMe

### ISSUE THREAD

**Issue by egoullaud** [chingu-voyages/v44-tier2-team-26#26]
**__ReadMe Description**
This is a robust document detailing our project. It will include a project description, tech used, screenshots or video walkthroughs of the project, design information, and an overview of the challenges we faced while building. We also will need to include instructions for anyone who would like to fork and work on this project to get them up and running. 

**__User Story__**
As a team member, I want to come here to see what needs to be added to the readMe. If there is something I think needs to be added, I will create a new check box item and add it to the list. If I have a question, I will leave a comment on this issue.

**__Things to Add__**
- [x] More tech icons to stack section! Nextjs, Tailwind
- [x] Remove Keith's information and add JLi1369's info
- [ ] Want to Contribute? Contribution Guidelines
- [ ] Challenges we faced/overcame
- [ ] Inside of the Tech section, include libraries we used! (so far: react-icons)
- [ ] Areas of improvement
- [ ] Next Steps (future additions/features)

**__Additional Considerations__**
