### ISSUE TITLE
Accessibility Checklist for the Project 

### ISSUE THREAD

**Issue by rselvasoyak** [chingu-voyages/v44-tier2-team-26#44]
**__Task Description__**
Checking off all these items off before releasing the project for accessibility concerns in relation to issue #18 

**__Technical Considerations__** 
 - [ ] font size min 1.6rem
 - [ ] hover and focus states for intractable elements 
 - [ ] Form accessibility check 
 - [ ] Clear instructions: Provide clear and concise instructions for playing the game. This is especially important for users with cognitive disabilities.
 - [ ] Colorblindness: Avoid relying on color alone to convey information, as this can create difficulties for users with color blindness.
 - [ ] User feedback: Provide clear and consistent feedback to the user about their actions and the status of the game. (Sweet Alerts?)

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.
