### ISSUE TITLE
Feature: Bot Designers

### ISSUE THREAD

**Issue by egoullaud** [chingu-voyages/v44-tier2-team-26#51]
## Feature Description ##
Panels for user to customize their bots: Four bot panels with controls to allow the user to input a unique bot name, select its Boolean value and operation, select the bots speed using a slider, and a dropdown to specify its starting direction - North, South, East, West

## User Story ##
As a user, I want to 1) control how my bots are named 2) select each bot's Boolean value AND operation and 3) select each bot's starting direction. If I choose not to do so, I want my bots to have preset/randomly-generated names, Boolean values, and starting directions.

#### High Priority ####
- [ ] Bot information is stored as a state within top app component (referencing JSON component)
  - [x] User can enter a unique name for each bot into an input text box
  - [ ] User will see an error message (preventing submission) if the name submitted is the same name assigned to another bot
  - [ ] User can select the Boolean value (0 or 1) from a dropdown for each bot
  - [ ] User can select a bot's starting direction from the direction dropdown
- [ ] Ensure that bot name can be passed as prop to display on scoreboard

#### Medium Priority ####
- [ ] User can see the bot randomly assigned to a tile in the arena once it has been created
- [ ] For each bot that the user doesn't enter a name, ensure that a unique identifier name is pre-populated and displayed (ex: Bot 1, Bot 2, etc.)
- [ ] For each bot that the user doesn't give a Boolean value, give it a random one upon bot generation/creation
- [ ] For each bot that the user doesn't give a starting direction, give it a random one upon bot generation/creation

#### Low Priority ####
- [ ] As the user is typing, check bot name against already-recorded/created bot names so that user does not need to click "Create Bot" to find out that the name is taken/unavailable

## Additional Considerations ##
- Consider adding feature for user to store bot information to persist past current session (ex: if they refresh the window)
