### ISSUE TITLE
Feature: Extras (Not Required)

### ISSUE THREAD

**Issue by egoullaud** [chingu-voyages/v44-tier2-team-26#52]
**__Feature Description__**
Not Requred, but would be fun to add if we have time! 

**__Tasks__**

- [ ]  User can see a log panel displaying the details of game milestones.
- [ ] Hint: This may be useful to the Developer during development and debugging.
- [ ]  User can see a game clock displaying current elapsed game time that is  updated every second.
- [ ]  User may choose a bots starting direction as North, Northeast, Southeast, South, Southwest, West, or Northwest.
- [ ]  User may specify the dimensions of the arena.
- [ ]  User may select an unique icon for a bot from a palette of icons. Icons n the palette are disabled once they are assigned.
- [ ]  User can see the bot with the most wins highlighted in some way in the Leaderboard.

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
